### PR TITLE
Sort lines and insert headers for gnuplot.

### PR DESCRIPTION
**Pull request by athas**

### CODE REVIEW

**Comment by athas** [comment]
MLKit:

mlkit


MPL:

mpl

Note that the order is now different.

**Comment by melsman** [comment]
Nice! I wonder how `vpmsort` and `pmsort` performs with the par0
runtime-system! Maybe also `mandelbrot` works with the par0 runtime...
Also, what machine are you using? Can we try on the computerome system, do
you think - it would be great to inspect scalability using upto 40 cores...

**Comment by athas** [comment]
I'm just using my Ryzen 1700X for now.  I wanted to make the scripts reliable before I try to run them on a batch system (but I already got both MPL and MLKit running on Computerome, which was actually a bit tricky).

**Comment by athas** [comment]
Remind me, what is the par0 runtime?  Is what the Makefile calls `-mlb-subdir C1`?

**Comment by melsman** [comment]
The `par0` runtime is the one where allocation in a region is not atomic; it works only for benchmarks where each region is allocated into only by at most one thread at a time. For the mlkit to select this version of the runtime system, pass the options `-par -par0`; see the `par_benchmarks/README.md` for examples...

**Comment by athas** [comment]
For a start, here's 40-core scaling on Computerome (the ordinary `par` runtime):

image

Looks like my sorting doesn't work as well as I expected.

The missing data points are programs that fail with `findLine: cannot find line with string 'Maximum resident set size'`, and it looks like `mlkit-bench` supresses the actual error.

**Comment by athas** [comment]
I added my scripts to the PR.  They are all in a separate `scripts/` directory, so not invasive at all.

**Comment by athas** [comment]
Fixed some things, so now everything runs with 40 threads, which also means the sorting is correct.

image

**Comment by athas** [comment]
Here is MPL.  I wonder what goes on after 20 threads...

image

**Comment by melsman** [comment]
Interesting.. I wonder why fib is not scaling better in our case - it is
not allocating at all!!

**Comment by melsman** [comment]
hmm - I guess it's ok with fib, but we should be able to do better with
mandelbrot, for example... Mandelbrot also works with -par0...

**Comment by melsman** [comment]
For mandelbrot, maybe we're hit by the irregularity of the problem at high
Ps - we should at least choose a P (the P in a gcs that is) that is two (or
four) times as large as the number of available cores... Perhaps we're just
really hit by not having a good scheduler... On the other hand, why
shouldn't MPL be affected by this issue also?!

**Comment by melsman** [comment]
@athas: It turns out we were using quite low -P defaults for many of the
benchmarks, which I think explains some of the bad speedups for high Ps....

**Comment by athas** [comment]
I'll rerun if you fix it!  I'm a little bit hesitant about the MPL results too, since these benchmarks are tuned for MLKit.  We'd certainly have to phrase it carefully if we include them.

**Comment by melsman** [comment]
... its fixed...

fre. 26. feb. 2021 kl. 11.42 skrev Troels Henriksen <
notifications@github.com>:

**Comment by athas** [comment]
Alright, I've put the pot on the stove.  Should take about an hour to cook this graph, though.

**Comment by athas** [comment]
image

I need to figure out why the `par0` version doesn't finish.  I probably screwed up in my scripts...

**Comment by melsman** [comment]
Programs that should work with par0 include `mandelbrot`, `vpmsort`,
`pmsort`, and `fib`.. When we hit 20 threads is that when hyperthreading
kicks in, you think?

**Comment by athas** [comment]
As far as I can see, these machines have hyperthreading disabled.  They certainly have 40 physical cores.

**Comment by melsman** [comment]
hmm - could it be that the absolute numbers are simply too small for us to
see any real gains? For the mandelbrot example, for instance, running on my
macbook pro, I get
```
$ /usr/bin/time ./mandelbrot-par0.exe
-f not passed, so not writing image to file.
        0.26 real         1.88 user         0.02 sys
```
With 10-times more cores, the absolute times could potentially become quite
small... With 4(8) cores, the program seems to scale quite well, but what
happens on the 40-cores system??

**Comment by athas** [comment]
Yes, I had the same thought.  Usually you also increase the total amount of work when you do these speedup measurements (i.e. you measure [weak scaling](https://en.wikipedia.org/wiki/Scalability#Weak_versus_strong_scaling)).  Doing that here will be tricky, since not all of the benchmarks have an obvious way to just dial up the amount of work done, and the tooling doesn't support it either.  The alternative is to just increase the base workload.

I think we should have a real-time conversation about what we intend to report, and on which machines, so I can focus my work and investigations.  We don't have that much time, after all.

**Comment by melsman** [comment]
Do you have time now?

**Comment by athas** [comment]
No.  But I will have time later this evening, and at pretty much any time in the coming days.

**Comment by melsman** [comment]
Will 20:00 tonight work for you?

**Comment by athas** [comment]
Yes.  I'll call you on Skype!

**Comment by melsman** [comment]
Is zoom ok - I don't think skype works for me...

**Pull request merged**
