### PR TITLE
Add speedup tool.

### PR DESCRIPTION
**Pull request by athas**
With this, it is fairly straightforward to produce data files that can be fed to gnuplot.  The scripts to do so are not part of this PR, but I tried it on my own machine and got this result:
mlkit

### CODE REVIEW

**Comment by melsman** [comment]
Nice!

**Comment by melsman** [comment]
Would it make sense to sort the benchmark list to the right of the graph according to their speedup factor on Nmax (i.e., 8) cores? It is somewhat difficult to identify which of the benchmarks perform poorly...

**Comment by athas** [comment]
My worry is that sorting them is a bad idea when we have a plot per compiler (at least the two MLKit variants, and maybe also MPL).  It will be very confusing if the colours don't match up.

**Comment by athas** [comment]
In the meantime, here's a speedup plot for MPL.

mpl

**Pull request merged**
